## node configurations
node:
  ## the type of spacex: authority/full
  chain: "authority"
  ## the type of storage: disable/enable
  storage: "enable"
  ## the type of sfrontend: disable/isolation/member
  sfrontend: "disable"
  ## the type of ipfs: disable/enable
  ipfs: "disable"

## identity configurations
identity:
  ## the backup of chain account
  backup: ''
  ## the password of chain account
  password: ""

## chain configurations
chain:
  ## the name of chain node
  name: "spacex-node"
  ## the port of chain node
  port: 30888

api:
  ## the url for chain
  ws: "ws://127.0.0.1:19944"
